ignore:
  - "tests/"
  - "examples/"
  - "build/" # Ignore any build artifacts
  - "scripts/" # Ignore helper scripts

# Pull Request Comment Configuration (Optional)
# This controls the comment that Codecov posts on your pull requests.
comment:
  layout: "reach, diff, files"
  behavior: default # "default" will update an existing comment or post a new one.
  require_changes: false # Post a comment even if coverage did not change.
