name: CI Check version consistency

on: [push, pull_request]

jobs:
  check-version:
    name: check-version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        # Pinned revision (v4.4.0)
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with:
          persist-credentials: false

      - name: Check that all version numbers agree
        run: python3 scripts/release.py check
